Création des templates d'email pour CartoBio
betagouv/signup-back pull request #170
Opened 2020-11-10 10:48 UTC by oncletom

cc @mtlde.

2020-11-17 11:02 UTC, oncletom commented
@mtlde j'ai modifié le template de refus pour que la raison du refus soit optionnelle. Si c'est optionnel, les raisons sont génériques et explicites - sur la base de ce que tu avais écrit dans le doc de rédaction !

2020-11-24 09:53 UTC, oncletom commented
@rdubigny c'est Ok pour merge de notre côté — je peux squash les commits si tu veux un historique clean.

2020-11-25 10:27 UTC, rdubigny requested changes
Hello @oncletom !

Merci pour cette PR, c'est vraiment chouette que tu t'appropries l'outils à ce point.

Cela dit, ça soulève des problème d'éditabilité dans Data Pass. Nottament, chaque template d'email est contenu dans un layout qui inclus un « bonjour » un lien vers la démarche et une signature (cf. https://github.com/betagouv/signup-back/blob/master/app/views/layouts/enrollment_mailer.text.erb).

Est ce que tu préfères coller au pattern actuel (on pourra faire une mise en prod plus vite) ou est ce que tu as besoin de personnaliser l'intégralité du mail (auquel cas, il faut que je fasse des petits devs et ça peut prendre plus de temps) ?

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/refuse_application.text.erb
> +Bonjour,
cette partie est incluse dans le fichier de layout : https://github.com/betagouv/signup-back/blob/master/app/views/layouts/enrollment_mailer.text.erb, elle ne doit donc pas apparaître ici, sinon il y aura 2 bonjours dans le mail.

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/refuse_application.text.erb
> +<% else %>
Cette partie pose problème parce qu'on ne peut pas faire apparaître le else dans le front. Je te suggère de ne pas mettre de else ici et de plutôt copier coller ce message toi même dans l'interface de Data Pass. Il devra apparaître en template dans une drop down au dessus du message au bout de 2 envois.

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/refuse_application.text.erb
> +Bonne journée,
même remarque pour le layout, cette partie est incluse dans https://github.com/betagouv/signup-back/blob/master/app/views/layouts/enrollment_mailer.text.erb

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +Bonjour,
inclus dans le layout

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +Bonne journée et à bientôt,
inclus dans le layout

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/validate_application.text.erb
> +Bonjour,
inclus dans le layout

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/validate_application.text.erb
> +Bonne journée,
inclus dans le layout

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +Pour voir ou modifier votre demande vous pouvez y accéder depuis ce lien : https://datapass.api.gouv.fr/<%= @target_api %>/<%= @enrollment_id %>
Le lien apparaît déjà dans le layout...

est ce que tu es certain de vouloir l'ajouter ici encore ?

2020-11-25 10:27 UTC, rdubigny commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +Pour voir ou modifier votre demande vous pouvez y accéder depuis ce lien : https://datapass.api.gouv.fr/<%= @target_api %>/<%= @enrollment_id %>
par ailleurs, tu peux utiliser la variable  `<%= @url %>` qui fait déjà la concaténation nécéssaire ;)

2020-11-25 10:28 UTC, rdubigny commented
> @rdubigny c'est Ok pour merge de notre côté — je peux squash les commits si tu veux un historique clean.

pas de soucis, je ferais le squash au moment de merger la PR.

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/refuse_application.text.erb
> +
```suggestion
```

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/refuse_application.text.erb
> +<% end %>
```suggestion
Nous ne distribuons pas de données nominatives ou permettant d'identifier les exploitations agricoles.
Nous ne distribuons pas de données en réponse à des traitements de données à caractère commercial.
Nous ne distribuons pas non plus les données à des projets qui ne participent pas au développement de l'Agriculture Biologique.
```

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/refuse_application.text.erb
> +L'équipe CartoBio
```suggestion
```

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +
```suggestion
```

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +Pour voir ou modifier votre demande vous pouvez y accéder depuis ce lien : https://datapass.api.gouv.fr/<%= @target_api %>/<%= @enrollment_id %>
```suggestion
```

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +L’équipe Cartobio
```suggestion
```

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/validate_application.text.erb
> +
```suggestion
```

2020-11-25 13:43 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/validate_application.text.erb
> +L'équipe CartoBio
```suggestion
```

2020-11-25 13:45 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/validate_application.text.erb
> +<% end %>
```suggestion

<%= @message %>
```

2020-11-25 13:46 UTC, oncletom commented
Ça roule, j'ai fait les modifs en fonction de ce que j'avais compris.

2020-11-26 16:33 UTC, rdubigny approved these changes
Hello @oncletom,

Merci pour cette PR ! Elle en déployée en production. Plus précisément, j'ai mergé ce commit : https://github.com/betagouv/signup-back/commit/f91f41650d2998c82e00b91e688f349298a62ac7 ; qui reprend tes changements mais en intégrant les contraintes de message obligatoire dans le cas d'un refus.

J'ai ajouter quelques suggestion supplémentaire pour améliorer encore plus ces mails.

N'hésites pas à revenir vers moi si tu as d'autres idées d'amélioration !

2020-11-26 16:33 UTC, closed without merging

2020-11-26 20:31 UTC, oncletom commented on app/views/enrollment_mailer/cartobio/send_application.text.erb
> +Toutes les demandes sont traitées sous 15 jours maximum.
C'est volontaire d'avoir mis 15 jours : on préfère donner la bonne surprise que ça soit plus rapide, plutôt que d'une mesure statistique qui ne reflète pas un rythme régulier.