Introduce webhooks for notifiers and bridges
betagouv/signup-back pull request #264
Opened 2021-08-05 13:43 UTC by skelz0r

Need merge of https://github.com/betagouv/signup-back/pull/249 before review/all iterations

FEEDME/WIP

* [ ] Introduce serializer for webhooks
* [ ] Refactor bridges
* [ ] Review
* [ ] Documentation

2021-08-10 11:57 UTC, skelz0r commented
@rdubigny it's OK.

I squashed commits and put some commits at the beginning of the PR which are mostly configurations. You can start with https://github.com/betagouv/signup-back/pull/264/commits/8e81ad0e7dbe86e1d7896ac32ab6cdf24979d60a ( `refactor: Bridge management in enrollment` ).

2021-08-10 12:00 UTC, skelz0r commented
FYI I introduced an `AbstractWebhookBridge` which is not currently used, I will use it for API Entreprise in another PR (which is a simple inheritance) when it'll be implemented on our dashboard.

2021-08-12 10:05 UTC, rdubigny requested changes
what a magnificent peace of architecture ! The resulting api entreprise webhook is very elegant and clean.

I got a few comments if you don't mind.

2021-08-12 10:05 UTC, rdubigny commented on docs/webhooks.md
> +### Partie 1: Datapass
Datapass => DataPass

I use this case everywhere else. I'll be delighted if we could keep consistency on this.

2021-08-12 10:05 UTC, rdubigny commented on docs/webhooks.md
> +Chacune des méthodes correspond à un événement asssocié à la demande datapass,
asssocié => associé

2021-08-12 12:18 UTC, skelz0r commented on config/routes.rb
> +  if Rails.env.development?
No reason, I can't remove this condition.

2021-08-12 12:19 UTC, skelz0r commented on config/routes.rb
> +  if Rails.env.development?
I can remove this condition* sorry

2021-08-12 12:20 UTC, skelz0r commented on app/models/enrollment.rb
> +    nil
;)

2021-08-12 12:21 UTC, skelz0r commented on app/mailers/webhook_mailer.rb
> +      subject: "[Datapass] Votre webhook endpoint est en défaut",
tbh I think you should handle all the wordings for this email, I invite you to make a commit directly.

2021-08-12 12:31 UTC, skelz0r commented on app/workers/deliver_enrollment_webhook_worker.rb
> +    reschedule_worker(target_api, payload, enrollment_id, tries_count)
Yes we keep trying, but we send only one email.

2021-08-12 12:46 UTC, skelz0r commented on docs/webhooks.md
> +Ci dessous un exemple (en ruby/rails) qui vérifie la valeur du `X-Hub-Signature:`
Yes will do

2021-08-12 12:56 UTC, skelz0r commented on app/serializers/webhook_enrollment_serializer.rb
> +  has_many :events, serializer: WebhookEventSerializer
I have no real opinions, if you think it may be relevant let's add it. There's no real issue about performance here btw

2021-08-12 13:05 UTC, skelz0r commented
I make all the requested change except the mail's wording, I think you should to it @rdubigny

2021-08-12 13:38 UTC, rdubigny approved these changes

2021-08-12 15:56 UTC, skelz0r commented
I just converted it to a draft, just in case

2021-08-31 13:24 UTC, closed without merging